name: Auto-Merge
on:
  workflow_run:
    workflows: [test]
    types:
      - completed
env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://Fjerdiness:${{secrets.GITHUB_TOKEN}}@github.com/Fjerdiness/Dummy_ultimateqa.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: WIP

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/Fjerdiness/Dummy_ultimateqa.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with main
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Fjerdiness"
        git config user.email "vocable_courts.05@icloud.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
