name: Playwright Tests
on:
  push:
    branches: [ WIP ]
  pull_request:
    branches: [ main, master ]
jobs:    
  job1:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
name: automerge
  job2:
    needs: job1
    automerge:
      runs-on: ubuntu-latest
      steps:
        - id: automerge
          name: automerge
          uses: "pascalgn/automerge-action@v0.15.5"
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
